# Generated by Django 4.2.3 on 2023-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcepie_name', models.CharField(max_length=100)),
                ('recepie_description', models.TextField()),
                ('recpie_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
